package com.dao.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DB_DETAIL".
 */
public class DbDetail {

    private Integer id;
    private Integer count;
    private Integer fcount;
    private Integer loreclass;
    private Integer rcount;
    private String img;
    private Long time;
    private String keywords;
    private String description;
    private String message;
    private String title;

    public DbDetail() {
    }

    public DbDetail(Integer id) {
        this.id = id;
    }

    public DbDetail(Integer id, Integer count, Integer fcount, Integer loreclass, Integer rcount, String img, Long time, String keywords, String description, String message, String title) {
        this.id = id;
        this.count = count;
        this.fcount = fcount;
        this.loreclass = loreclass;
        this.rcount = rcount;
        this.img = img;
        this.time = time;
        this.keywords = keywords;
        this.description = description;
        this.message = message;
        this.title = title;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getFcount() {
        return fcount;
    }

    public void setFcount(Integer fcount) {
        this.fcount = fcount;
    }

    public Integer getLoreclass() {
        return loreclass;
    }

    public void setLoreclass(Integer loreclass) {
        this.loreclass = loreclass;
    }

    public Integer getRcount() {
        return rcount;
    }

    public void setRcount(Integer rcount) {
        this.rcount = rcount;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
