package com.nabt.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.nabt.db.bean.DBook;

import com.nabt.db.dao.DBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBookDaoConfig;

    private final DBookDao dBookDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBookDaoConfig = daoConfigMap.get(DBookDao.class).clone();
        dBookDaoConfig.initIdentityScope(type);

        dBookDao = new DBookDao(dBookDaoConfig, this);

        registerDao(DBook.class, dBookDao);
    }
    
    public void clear() {
        dBookDaoConfig.getIdentityScope().clear();
    }

    public DBookDao getDBookDao() {
        return dBookDao;
    }

}
