package com.dao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.dao.entity.DbDetail;

import com.dao.db.DbDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbDetailDaoConfig;

    private final DbDetailDao dbDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbDetailDaoConfig = daoConfigMap.get(DbDetailDao.class).clone();
        dbDetailDaoConfig.initIdentityScope(type);

        dbDetailDao = new DbDetailDao(dbDetailDaoConfig, this);

        registerDao(DbDetail.class, dbDetailDao);
    }
    
    public void clear() {
        dbDetailDaoConfig.getIdentityScope().clear();
    }

    public DbDetailDao getDbDetailDao() {
        return dbDetailDao;
    }

}
