package com.nabt.cook.dao.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.nabt.cook.dao.entity.Book;

import com.nabt.cook.dao.entity.Step;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STEP".
*/
public class StepDao extends AbstractDao<Step, Void> {

    public static final String TABLENAME = "STEP";

    /**
     * Properties of entity Step.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Img = new Property(0, String.class, "img", false, "IMG");
        public final static Property Step = new Property(1, String.class, "step", false, "STEP");
        public final static Property BookId = new Property(2, String.class, "bookId", false, "BOOK_ID");
    };

    private DaoSession daoSession;

    private Query<Step> book_StepsQuery;

    public StepDao(DaoConfig config) {
        super(config);
    }
    
    public StepDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STEP\" (" + //
                "\"IMG\" TEXT," + // 0: img
                "\"STEP\" TEXT," + // 1: step
                "\"BOOK_ID\" TEXT);"); // 2: bookId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STEP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Step entity) {
        stmt.clearBindings();
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(1, img);
        }
 
        String step = entity.getStep();
        if (step != null) {
            stmt.bindString(2, step);
        }
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(3, bookId);
        }
    }

    @Override
    protected void attachEntity(Step entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Step readEntity(Cursor cursor, int offset) {
        Step entity = new Step( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // img
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // step
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // bookId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Step entity, int offset) {
        entity.setImg(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStep(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBookId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Step entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Step entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "steps" to-many relationship of Book. */
    public List<Step> _queryBook_Steps(String bookId) {
        synchronized (this) {
            if (book_StepsQuery == null) {
                QueryBuilder<Step> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BookId.eq(null));
                book_StepsQuery = queryBuilder.build();
            }
        }
        Query<Step> query = book_StepsQuery.forCurrentThread();
        query.setParameter(0, bookId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBookDao().getAllColumns());
            builder.append(" FROM STEP T");
            builder.append(" LEFT JOIN BOOK T0 ON T.\"BOOK_ID\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Step loadCurrentDeep(Cursor cursor, boolean lock) {
        Step entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Book book = loadCurrentOther(daoSession.getBookDao(), cursor, offset);
        entity.setBook(book);

        return entity;    
    }

    public Step loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Step> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Step> list = new ArrayList<Step>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Step> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Step> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
